In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
#import seaborn as sns
#sns.set_style('whitegrid')
#plt.style.use("fivethirtyeight")
%matplotlib inline

df = pd.read_csv('Dataframes/3rdBodyPerturbationPoliastro.csv')
df_v = pd.read_csv('Dataframes/3rdBodyPerturbationPoliastro_vv.csv')

df['vv_x']=df_v.vv_x
df['vv_y']=df_v.vv_y
df['vv_z']=df_v.vv_z

In [20]:
df # Full 6D r,v elements

                x             y             z      vv_x      vv_y      vv_z
0    42159.783600      0.000000      0.000000  0.000000  3.074505  0.053666
1    39159.545914  15563.916303    266.913399 -1.142984  2.852848  0.048528
2    30572.229294  28909.053086    496.928223 -2.127756  2.228986  0.039518
3    17596.068412  38144.740319    671.356184 -2.813645  1.287415  0.027234
4     2068.446366  41949.706443    775.646554 -3.098444  0.161675  0.012698
..            ...           ...           ...       ...       ...       ...
995  38132.961517  21370.880108  -7532.333000 -0.876644  2.199413  1.750026
996  31399.515894  31233.289707   1828.575655 -1.692745  1.562118  1.820311
997  20906.077447  37238.565267  10967.804062 -2.312211  0.726117  1.664753
998   7871.245318  38575.122415  18731.818721 -2.661184 -0.221639  1.293445
999  -6142.526530  34919.272230  24066.202237 -2.681132 -1.179765  0.734721

[1000 rows x 6 columns]

Function to train model on ONE column: